{% set name = "pybcj" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70bbe2dc185993351955bfe8f61395038f96f5de92bb3a436acb01505781f8f2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=58
    - setuptools-scm >=6.0.1
    - wheel
  run:
    - importlib-metadata  # [py<38]
    - python
  run_constrained:
    - mypy >=1.10.0
    - flake8 <5

test:
  imports:
    - bcj
  commands:
    - pip check
  requires:
    - pip

about:
  description: |
    In data compression, BCJ, short for Branch-Call-Jump, refers to a technique that improves
    the compression of machine code of executable binaries by replacing relative branch
    addresses with absolute ones. This allows a LZMA compressor to identify duplicate targets
    and archive higher compression rate.
  home: https://codeberg.org/miurahr/pybcj
  dev_url: https://codeberg.org/miurahr/pybcj
  doc_url: https://codeberg.org/miurahr/pybcj/src/branch/main/README.rst
  summary: bcj filter library
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
