{% set name = "pybcj" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14839501653ffea75668ab50ceea1df576d3a83f0587cdeaab56a423c8b1b097

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=42.0
    - setuptools-scm >=3.5.0
  run:
    - importlib-metadata  # [py<38]
    - python

test:
  imports:
    - bcj
    - bcj.c
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/miurahr/pybcj
  summary: bcj filter library
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
