{% set name = "pybcj" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72d64574069ffb0a800020668376b7ebd7adea159adbf4d35f8effc62f0daa67

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=58
    - setuptools-scm >=6.0.1
    - toml
  run:
    - python
  run_constrained:
    - mypy >=1.10.0
    - flake8 <5

# Running pytest was deleted because  pypi package does not include tests folder. It is only available in the source code repository.
test:
  imports:
    - bcj
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://codeberg.org/miurahr/pybcj
  description: |
    In data compression, BCJ, short for Branch-Call-Jump, refers to a technique that improves
    the compression of machine code of executable binaries by replacing relative branch
    addresses with absolute ones. This allows a LZMA compressor to identify duplicate targets
    and archive higher compression rate.
  summary: bcj filter library
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  dev_url: https://codeberg.org/miurahr/pybcj
  doc_url: https://codeberg.org/miurahr/pybcj/src/branch/main/README.rst

extra:
  recipe-maintainers:
    - sarthakpati
